# Arreglos con NumPy

In [1]:
# Importamos la paquetería
from numpy import array

# Creamos el arreglo
l = [1.0, 2.0, 3.0]
a = array(l)

# Enseñamos el contenido
print(a)
# Enseñamos la forma del arreglo
print(a.shape)
# Enseñamos el tipo de arreglo
print(a.dtype)

[1. 2. 3.]
(3,)
float64


La primera salida resulta ser el contenido del arreglo.
La segunda salida resulta ser el tamaño del arreglo, éste es un arreglo unidimensional con tres elementos.
Por último, muestra el tipo de objeto que guarda, el "float64" indica un objeto de punto flotante.

## Funciones para Crear Arreglos

In [2]:
# Creamos un arreglo vacío
from numpy import empty
a = empty([3,3])
print(a)

[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 5.93e-321]
 [0.00e+000 0.00e+000 0.00e+000]]


In [3]:
# Creamos un arreglo de ceros
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# Creamos un arreglo de unos
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


## Unión de Arreglos

### Stack Vertical

In [5]:
# Crear un arreglo con vstack
from numpy import array
from numpy import vstack
# Crea el primer arreglo
a1 = array([1,2,3])
print(a1)
# Crea el segundo arreglo
a2 = array([4,5,6])
print(a2)
# Hacemos la unión en stack vertical
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


Véase que al imprimir la forma del arreglo, da como resultado uno de dos renglones y tres columnas.

### Stack Horizontal

In [6]:
# Unión horizontal de arreglos
from numpy import array
from numpy import hstack
# Crea el primer arreglo
a1 = array([1,2,3])
print(a1)
# Crea el segundo arreglo
a2 = array([4,5,6])
print(a2)
# Crea la unión horizontal
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


Véase que al imprimir la forma del arreglo, da como resultado un arreglo unidimensional con 6 elementos.