# Broadcasting de Arreglos

Si se tienen dos arreglos de distintos tamaños, no se pueden sumar o en general, no se pueden utilizar para realizar aritmética. Una manera de pasar esta limitación consiste en duplicar el arreglo de tamaño menor para que tenga la dimensión y el tamaño del más grande. 

## Limitaciones con la Aritmética de Arreglos

Se pueden realizar operaciones de adición o substracción entre arreglos. Veamos un simple ejemplo de esto. Sin embargo, sólo se puede realizar si el tamaño de los arreglos es el mismo.

In [1]:
import numpy as np

# Creamos dos arreglos
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Sumamos los arreglos y los imprimimos
c = a + b
print(c)

[5 7 9]


## Array Broadcasting

Para arreglar el problema expuesto, NumPy nos da un método que se le onoce como *BroadCasting* que permite realizar operaciones aritméticas con arreglos de diferente tamaño. Esto lo logra modificando el tamaño del arreglo pequeño de tal manera que queden los arreglos de la misma dimensión. En realidad NumPy sólo asigna memoria y realiza operaciones eficientes.


## Broadcasting en NumPy

Para ejemplificar el funcionamiento del método, veremos unos ejemplos.

In [2]:
# Creamos un arreglo y un escalar
a = np.array([1, 2, 3])
b = 2

# Realizamos el broadcast
c = a + b # Aquí crea un arreglo de tres entradas con el valor de b
print(c)

[3 4 5]


## Escalares y Arreglos Bidimensionales

También se puede aplicar el broadcasting a arreglos multidimensionales, veamos el siguiente ejemplo.

In [6]:
# Creamos el arreglo
A = np.array([[1, 2, 3],
             [4, 5, 6]])
print(A)

# Realizamos el broadcast
B = A + b
print(B)

# También probamos con un arreglo de distinta dimensión
b = np.array([1, 2, 3])
B = A + b
print(B)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]
[[2 4 6]
 [5 7 9]]


## Limitaciones del Broadcasting

Lamentablemente, el broadcasting no siempre se puede utilizar, pues establece una regla para su correcto funcionamiento. El broadcasting podrá ser utilizado únicamente si la dimensión de los arreglos es de al menos uno. Esto aplica de manera análoga para cuando se trata de arreglos bidimensionales, considerando los renglones y columnas. Hagamos un ejemplo en donde el broadcasting falla.

In [7]:
# Veamos el arreglo A y su forma
print(A)
print(A.shape)

# Hacemos una variable no compatible
b = np.array([1, 2])
print(b.shape)

# Intentamos hacer el broadcast
C = A + b
print(C)

[[1 2 3]
 [4 5 6]]
(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 